Repository Screenly/Playground, pull requests merged in 2025-09, with the labels that each got.

#402 chore: enable creation of Dependabot PRs for the Edge App template
  .github/dependabot.yml
Labels: 🙌 enhancement, Review effort 2/5

#410 chore: rename the Google Calendar app to just the calendar Edge App
  edge-apps/blueprint/scripts/cors-proxy-server.js
  edge-apps/blueprint/ts/vite-plugins/index.ts
  edge-apps/blueprint/ts/vite-plugins/watch-mock-data.ts
  edge-apps/calendar/.editorconfig
  edge-apps/calendar/.gitattributes
  edge-apps/calendar/.gitignore
  edge-apps/calendar/.prettierrc.json
  edge-apps/calendar/.vscode/extensions.json
  edge-apps/calendar/README.md
  edge-apps/calendar/bun.lock
  edge-apps/calendar/e2e/tsconfig.json
  edge-apps/calendar/e2e/vue.spec.ts
  edge-apps/calendar/eslint.config.ts
  edge-apps/calendar/index.html
  edge-apps/calendar/package.json
  edge-apps/calendar/playwright.config.ts
  edge-apps/calendar/public/favicon.ico
  edge-apps/calendar/public/fonts/Aeonik-Regular.woff
  edge-apps/calendar/public/fonts/Aeonik-Regular.woff2
  edge-apps/calendar/screenly.yml
  edge-apps/calendar/screenly_qc.yml
  edge-apps/calendar/src/App.vue
  edge-apps/calendar/src/assets/calendar-overview.scss
  edge-apps/calendar/src/assets/daily-calendar-view.scss
  edge-apps/calendar/src/assets/font/Aeonik-Regular.woff
  edge-apps/calendar/src/assets/font/Aeonik-Regular.woff2
  edge-apps/calendar/src/assets/main.scss
  edge-apps/calendar/src/assets/monthly-calendar-view.scss
  edge-apps/calendar/src/assets/weekly-calendar-view.scss
  edge-apps/calendar/src/components/CalendarOverview.vue
  edge-apps/calendar/src/components/DailyCalendarView.vue
  edge-apps/calendar/src/components/EventTimeRange.vue
  edge-apps/calendar/src/components/MonthlyCalendarView.vue
  edge-apps/calendar/src/components/WeeklyCalendarView.vue
  edge-apps/calendar/src/components/__tests__/App.spec.ts
  edge-apps/calendar/src/constants.ts
  edge-apps/calendar/src/events.ts
  edge-apps/calendar/src/img/icon.svg
  edge-apps/calendar/src/main.ts
  edge-apps/calendar/src/mocks/lz-ts-mock.ts
  edge-apps/calendar/src/stores/calendar.ts
  edge-apps/calendar/src/stores/settings.ts
  edge-apps/calendar/src/test-setup.ts
  edge-apps/calendar/src/utils.ts
  edge-apps/calendar/static/images/authorization-code.png
  edge-apps/calendar/static/images/enable-google-calendar-api.png
  edge-apps/calendar/tsconfig.app.json
  edge-apps/calendar/tsconfig.json
  edge-apps/calendar/tsconfig.node.json
  edge-apps/calendar/tsconfig.vitest.json
  edge-apps/calendar/vite.config.ts
  edge-apps/calendar/vitest.config.ts
  edge-apps/google-calendar/README.md
  edge-apps/google-calendar/src/img/icon.svg
Labels: 🙌 enhancement, Review effort 4/5, Possible security concern

#419 chore(ci): add support for deleting missing settings when updating Edge Apps
  .github/workflows/update-edge-app.yml
Labels: 🙌 enhancement, Review effort 2/5

#428 Moved: powerbi to powerbi-legacy
  README.md
  edge-apps/powerbi-legacy/.ignore
  edge-apps/powerbi-legacy/README.md
  edge-apps/powerbi-legacy/index.html
  edge-apps/powerbi-legacy/powerbi.min.js
  edge-apps/powerbi-legacy/screenly.yml
  edge-apps/powerbi-legacy/screenly_qc.yml
  edge-apps/powerbi-legacy/static/images/icon.svg
Labels: Review effort 2/5
