Repository Screenly/Playground, pull requests merged in 2025-04, with the labels that each got.

#218 New TFL Bus App with Brand Fetching Features
  edge-apps/tfl-bus-status/.ignore
  edge-apps/tfl-bus-status/index.html
  edge-apps/tfl-bus-status/screenly.yml
  edge-apps/tfl-bus-status/screenly_qc.yml
  edge-apps/tfl-bus-status/static/fonts/Aeonik-Medium.woff
  edge-apps/tfl-bus-status/static/fonts/Aeonik-Medium.woff2
  edge-apps/tfl-bus-status/static/fonts/Aeonik-Regular.woff
  edge-apps/tfl-bus-status/static/fonts/Aeonik-Regular.woff2
  edge-apps/tfl-bus-status/static/images/bus-icon.svg
  edge-apps/tfl-bus-status/static/images/clock-icon.svg
  edge-apps/tfl-bus-status/static/images/screenly.svg
  edge-apps/tfl-bus-status/static/js/alpinejs-3.13.0.min.js
  edge-apps/tfl-bus-status/static/js/script.js
  edge-apps/tfl-bus-status/static/styles/common.css
  edge-apps/tfl-bus-status/static/styles/style.css
Labels: Review effort 4/5

#225 Add Location Information in Weather App.
  edge-apps/weather/index.html
  edge-apps/weather/static/fonts/Inter-Medium.woff2
  edge-apps/weather/static/fonts/Inter-Regular.woff2
  edge-apps/weather/static/fonts/Inter-SemiBold.woff2
  edge-apps/weather/static/images/location-pin-icon.svg
  edge-apps/weather/static/js/main.js
  edge-apps/weather/static/styles/common.css
  edge-apps/weather/static/styles/styles.css
Labels: enhancement, Review effort 4/5

#226 Add Signal Ready on IFrame App
  edge-apps/iframe/screenly.yml
  edge-apps/iframe/screenly_qc.yml
  edge-apps/iframe/static/js/main.js
Labels: enhancement, Review effort 1/5

#227 Improve Weather App's Ready Signal Implementation and Update Docs.
  edge-apps/weather/README.md
  edge-apps/weather/screenly.yml
  edge-apps/weather/screenly_qc.yml
  edge-apps/weather/static/images/weather-app-preview.png
  edge-apps/weather/static/js/main.js
Labels: 🐞 bug, 🙌 enhancement, Review effort 2/5

#230 Exclude .svg files from JSCPD to avoid false positives
  .github/linters/.jscpd.json
Labels: Review effort 1/5

#228 Updated Edge App Icons.
  edge-apps/countdown-timer/screenly.yml
  edge-apps/countdown-timer/screenly_qc.yml
  edge-apps/countdown-timer/static/img/icon.svg
  edge-apps/iframe/static/images/icon.svg
  edge-apps/rss-reader/static/img/icon.svg
  edge-apps/simple-message-app/screenly.yml
  edge-apps/simple-message-app/screenly_qc.yml
  edge-apps/simple-message-app/static/img/icon.svg
  edge-apps/tfl-bus-status/static/images/clock-icon.svg
  edge-apps/tfl-bus-status/static/images/icon.svg
  edge-apps/weather/static/images/icon.svg
Labels: 🙌 enhancement, Review effort 1/5

#231 Fix Docs and TFL App Internal asset
  edge-apps/tfl-bus-status/README.md
  edge-apps/tfl-bus-status/static/images/clock-icon.svg
  edge-apps/tfl-bus-status/static/images/tfl-bus-status-app-preview.png
  edge-apps/weather/README.md
Labels: 🐞 bug, 🙌 enhancement, Review effort 1/5

#224 New Welcome Edge App with Brand Fetching Features
  README.md
  edge-apps/welcome-app/README.md
  edge-apps/welcome-app/index.html
  edge-apps/welcome-app/screenly.yml
  edge-apps/welcome-app/screenly_qc.yml
  edge-apps/welcome-app/static/css/common.css
  edge-apps/welcome-app/static/css/style.css
  edge-apps/welcome-app/static/fonts/Inter-Medium.woff2
  edge-apps/welcome-app/static/fonts/Inter-Regular.woff2
  edge-apps/welcome-app/static/fonts/Inter-SemiBold.woff2
  edge-apps/welcome-app/static/img/Screenly.svg
  edge-apps/welcome-app/static/img/icon.svg
  edge-apps/welcome-app/static/img/welcome-app-preview.png
  edge-apps/welcome-app/static/js/country-locale-map.1.18.5.min.js
  edge-apps/welcome-app/static/js/main.js
  edge-apps/welcome-app/static/js/moment-timezone-with-data.min.js
  edge-apps/welcome-app/static/js/moment-with-locales.min.js
  edge-apps/welcome-app/static/js/offline-geocode-city-1.0.2.min.js
  edge-apps/welcome-app/static/js/tz.min.js
Labels: Review effort 4/5, 🎉 New App

#232 Vibe coding a queue management
  edge-apps/queue-management-system/README.md
  edge-apps/queue-management-system/architecture.d2
  edge-apps/queue-management-system/architecture.svg
  edge-apps/queue-management-system/client/index.html
  edge-apps/queue-management-system/client/screenly.yml
  edge-apps/queue-management-system/server/Dockerfile
  edge-apps/queue-management-system/server/app/main.py
  edge-apps/queue-management-system/server/app/models.py
  edge-apps/queue-management-system/server/docker-compose.yml
  edge-apps/queue-management-system/server/requirements.txt
  edge-apps/queue-management-system/server/server.py
Labels: Review effort 3/5

#229 Bus Stop Lookup: Performance Optimizations and Copy Feature
  edge-apps/helpers/tfl/bus-stop-lookup/index.html
  edge-apps/helpers/tfl/bus-stop-lookup/script.js
  edge-apps/helpers/tfl/bus-stop-lookup/style.css
Labels: 🙌 enhancement, Review effort 4/5

#237 added missing TFL lookup page
  README.md
Labels: 🙌 enhancement, Review effort 1/5
