Repository Screenly/Playground, pull requests merged in 2025-05, with the labels that each got.

#235 Welcome App Workflow - For QC and Production.
  .github/workflows/deploy-welcome-app-qc.yml
  .github/workflows/deploy-welcome-app.yml
  edge-apps/welcome-app/screenly.yml
Labels: 🙌 enhancement, Review effort 1/5

#241 Update Production App YML For CI
  .github/workflows/deploy-welcome-app.yml
Labels: 🐞 bug, Review effort 1/5

#243 chore: write Cursor-related instructions
  .cursor/rules/general.mdc
  .cursor/rules/supported-resolutions.mdc
Labels: Review effort 1/5

#239 Analytics Dashboard Edge App
  .github/workflows/deploy-fake-dashboard-app-qc.yml
  .github/workflows/deploy-fake-dashboard-app.yml
  edge-apps/fake-dashboard/index.html
  edge-apps/fake-dashboard/screenly.yml
  edge-apps/fake-dashboard/screenly_qc.yml
  edge-apps/fake-dashboard/static/css/styles.css
  edge-apps/fake-dashboard/static/img/icon.svg
  edge-apps/fake-dashboard/static/js/script.js
Labels: Review effort 3/5, 🎉 New App

#216 feat: create a Google Calendar app
  edge-apps/google-calendar/.gitignore
  edge-apps/google-calendar/README.md
  edge-apps/google-calendar/package-lock.json
  edge-apps/google-calendar/package.json
  edge-apps/google-calendar/screenly.yml
  edge-apps/google-calendar/screenly_qc.yml
  edge-apps/google-calendar/src/components/analog-clock.css
  edge-apps/google-calendar/src/components/analog-clock.jsx
  edge-apps/google-calendar/src/components/calendar-overview.jsx
  edge-apps/google-calendar/src/components/daily-calendar-view.jsx
  edge-apps/google-calendar/src/components/info-card.jsx
  edge-apps/google-calendar/src/components/monthly-calendar-view.jsx
  edge-apps/google-calendar/src/components/weekly-calendar-view.css
  edge-apps/google-calendar/src/components/weekly-calendar-view.jsx
  edge-apps/google-calendar/src/constants.js
  edge-apps/google-calendar/src/css/common.css
  edge-apps/google-calendar/src/css/style.css
  edge-apps/google-calendar/src/events.js
  edge-apps/google-calendar/src/fonts/Aeonik-Regular.woff
  edge-apps/google-calendar/src/fonts/Aeonik-Regular.woff2
  edge-apps/google-calendar/src/img/icon.svg
  edge-apps/google-calendar/src/img/screenly.svg
  edge-apps/google-calendar/src/index.html
  edge-apps/google-calendar/src/index.jsx
  edge-apps/google-calendar/src/utils.js
  edge-apps/google-calendar/static/images/authorization-code.png
  edge-apps/google-calendar/static/images/enable-google-calendar-api.png
  edge-apps/google-calendar/webpack.common.js
  edge-apps/google-calendar/webpack.dev.js
  edge-apps/google-calendar/webpack.prod.js
Labels: Review effort 4/5, 🎉 New App

#250 chore(ci): bump `actions/checkout` from v3 to v4
  .github/workflows/deploy-asset-metadata-app-qc.yml
  .github/workflows/deploy-asset-metadata-app.yml
  .github/workflows/deploy-asset-metadata.yml
  .github/workflows/deploy-clock-app-qc.yml
  .github/workflows/deploy-clock-app.yml
  .github/workflows/deploy-countdown-timer-qc.yml
  .github/workflows/deploy-countdown-timer.yml
  .github/workflows/deploy-fake-dashboard-app-qc.yml
  .github/workflows/deploy-fake-dashboard-app.yml
  .github/workflows/deploy-github-pages.yml
  .github/workflows/deploy-iframe-qc.yml
  .github/workflows/deploy-iframe.yml
  .github/workflows/deploy-instagram.yml
  .github/workflows/deploy-power-bi-qc.yml
  .github/workflows/deploy-power-bi.yml
  .github/workflows/deploy-rss-reader-qc.yml
  .github/workflows/deploy-rss-reader.yml
  .github/workflows/deploy-simple-message-app-qc.yml
  .github/workflows/deploy-simple-message-app.yml
  .github/workflows/deploy-tfl-bus-status-qc.yml
  .github/workflows/deploy-tfl-bus-status.yml
  .github/workflows/deploy-weather-app-qc.yml
  .github/workflows/deploy-weather-app.yml
  .github/workflows/deploy-welcome-app-qc.yml
  .github/workflows/deploy-welcome-app.yml
  .github/workflows/linter.yml
Labels: Review effort 1/5

#251 chore(ci): fix workflow for deploying the calendar Edge App
  .github/workflows/deploy-calendar-app-qc.yml
  .github/workflows/deploy-calendar-app.yml
Labels: Review effort 1/5

#252 chore(ci): fix workflow for deploying the calendar Edge App
  .github/workflows/deploy-calendar-app-qc.yml
  .github/workflows/deploy-calendar-app.yml
Labels: Review effort 1/5

#253 chore(deps): bump `esbuild` to `>=0.25.0`
  edge-apps/google-calendar/package-lock.json
Labels: Review effort 1/5

#255 docs: update setup and deployment instructions for the calendar app
  edge-apps/google-calendar/README.md
  edge-apps/google-calendar/screenly.yml
  edge-apps/google-calendar/screenly_qc.yml
Labels: Review effort 2/5

#234 feat: Add 3D Text screensaver Edge App
  .github/workflows/deploy-3d-text-app-qc.yml
  .github/workflows/deploy-3d-text-app.yml
  README.md
  edge-apps/3d-text/README.md
  edge-apps/3d-text/index.html
  edge-apps/3d-text/screenly.yml
  edge-apps/3d-text/screenly_qc.yml
  edge-apps/3d-text/static/css/styles.css
  edge-apps/3d-text/static/img/icon.svg
  edge-apps/3d-text/static/js/main.js
Labels: Review effort 3/5, 🎉 New App

#258 Update 3D Text App Icon
  edge-apps/3d-text/static/img/icon.svg
Labels: 🙌 enhancement

#257 Fix Google Calendar App Icon
  edge-apps/google-calendar/screenly.yml
  edge-apps/google-calendar/screenly_qc.yml
Labels: 🙌 enhancement, Review effort 1/5

#259 Feat: Support Background color update in "3D Text Edge App"
  edge-apps/3d-text/README.md
  edge-apps/3d-text/screenly.yml
  edge-apps/3d-text/screenly_qc.yml
  edge-apps/3d-text/static/js/main.js
Labels: 🙌 enhancement, Review effort 2/5

#261 Updated fake dashboard ID
  edge-apps/fake-dashboard/screenly.yml
Labels: Review effort 1/5

#266 chore: write Cursor rules for generating CSS code
  .cursor/rules/css.mdc
Labels: Review effort 1/5
