Repository Screenly/Playground, pull requests merged in 2025-06, with the labels that each got.

#276 Fix Charlie App
  edge-apps/charlie-hr-app/screenly.yml
Labels: Review effort 1/5

#271 Fix Edge App Initialize Workflow
  .github/workflows/initialize-app.yml
  .github/workflows/update-edge-app.yml
  edge-apps/fake-dashboard/screenly.yml
  edge-apps/fake-dashboard/screenly_qc.yml
Labels: 🙌 enhancement, Review effort 3/5

#282 chore(ci): specify instance name when creating an Edge App instance
  .github/workflows/initialize-app.yml
Labels: 🙌 enhancement, Review effort 2/5

#279 Fix Charlie App setting title
  README.md
  edge-apps/charlie-hr-app/screenly.yml
  edge-apps/charlie-hr-app/screenly_qc.yml
  edge-apps/charlie-hr-app/static/js/tz.min.js
Labels: 🙌 enhancement, Review effort 2/5

#284 Update CharlieHR App Name
  edge-apps/charlie-hr-app/screenly.yml
  edge-apps/charlie-hr-app/screenly_qc.yml
Labels: 🙌 enhancement, Review effort 1/5

#285 Update Welcome App Icon
  edge-apps/welcome-app/static/img/icon.svg
Labels: 🙌 enhancement
